[package]
name = "tw-storage-extra"
description = "Additional feature implementation to access `cw-storage-plus` and `cosmwasm-storage`"
version = "0.1.2"
license = "Apache-2.0"
authors = ["TwilightCouncil"]
edition = "2021"
repository = "https://github.com/TwilightCouncil/twilight-standard"

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-std = { version = "0.16.7" }
cosmwasm-storage = { version = "0.16.7" }
cw-storage-plus = "0.9.1"
serde = { version = "1.0.136", default-features = false, features = ["derive"] }
